---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# fco2r

<!-- badges: start -->
<!-- badges: end -->

The goal of fco2r is to ...

## Installation

You can install the released version of fco2r from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("fco2r")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("arpanosso/fco2r")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(fco2r)
## basic example code
```

```{r}
oco2_br <- readr::read_rds("C://GitHub//fco2r//data-raw//oco2_br.rds")
dplyr::glimpse(oco2_br)
```

```{r}
oco2_br |>
  dplyr::sample_n(20000) |>
  ggplot2::ggplot(ggplot2::aes(x=longitude, y=latitude)) +
  ggplot2::geom_point()
```


